social_django/middleware.py

This is port of https://github.com/omab/python-social-auth/pull/1031 PR.

Subclass MiddlewareMixin for Django 1.10 compat

---

social_django/migrations/0001_initial.py
social_django/migrations/0002_add_related_name.py
social_django/migrations/0003_alter_email_max_length.py
social_django/migrations/0004_auto_20160423_0400.py
social_django/migrations/0005_auto_20160727_2333.py

Rename 'social_core' to 'social_auth' in Migration.replaces

---

social_django/storage.py

To avoid `django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.` in case the user already exists.

Use transaction.atomic() when creating user.

---

social_django/fields.py
social_django/migrations/0004_auto_20160423_0400.py
social_django/migrations/0006_partial.py

made default callable for JSONField

---

.travis.yml
social_django/compat.py
social_django/models.py
social_django/utils.py
tests/compat.py
tests/settings.py
tests/test_admin.py
tests/test_views.py
tests/urls.py
tox.ini

Related to #6 and #64. Still needs more tests for changes mentioned in #6.

Test on Python 3.6 and Django 2.0

---

social_django/compat.py
social_django/utils.py
social_django/views.py
tests/test_views.py

Add more view tests.

---

tests/compat.py
tests/test_models.py

Waiting for #93 to get merged with a fix for user model on Django 2.0+...

Add more model tests.

---

setup.py

I forgot to add the newly added module to setup.py in https://github.com/python-social-auth/social-app-django/pull/63...

Install management command module

---

social_django/middleware.py

Log exception as `INFO` if `django.contrib.messages` app is installed, if not log as `ERROR`.
This is to reduce noise, still in line with [the previous reasoning](https://github.com/omab/python-social-auth/issues/507) and [this commit](https://github.com/python-social-auth/social-app-django/commit/3eae711e60a025c3d02c84429adeab0911dffe9e).

Log less errors in SocialAuthExceptionMiddleware

---

social_django/views.py

Keyword missing in do_complete call resulting in None-type user.

Fix missing keyword argument in do_complete

---

.travis.yml
tox.ini

Update and simplify TravisCI and Tox definitions.

Simplify Travis and Tox definitions

---

setup.py

Simple one-liner to get the Markdown to display.

Make PyPI process the README as Markdown, #210

---

.github/workflows/flake8.yml

Use major version of GH actions
your code._

use major version of GH actions

---

requirements.txt
social_django/fields.py
social_django/middleware.py
social_django/storage.py

Remove six dependency, because in https://github.com/python-social-auth/social-app-django/commit/7e09f352aa09e47378ebaa998de26e5ab8f5bcb2 this project dropped support for Python 2, thus we no longer need compat between 2 and 3. Also bumped social-core version to 4.x which supports only Python 3.
- [x ] Refactoring (no functional changes, no api changes)
your code._

remove six dependency

---

social_django/compat.py
social_django/middleware.py

import MiddlewareMixin from django, then remove compat module.
your code._

import MiddlewareMixin from django

---

CHANGELOG.md

Changelog: Fix url to 4.0.0

---

social_django/context_processors.py
social_django/fields.py
social_django/middleware.py
social_django/strategy.py
tests/settings.py
tests/test_strategy.py
tests/urls.py

* The force_text is going to be removed in upcoming Django release.
* Replace deprecated urls.url with urls.path
* Replace deprecated ugettext_lazy with gettext_lazy
* Use urllib.parse.quote instead of deprecated urlquote
your code._

Django depreciations fixes

---

setup.py

Otherwise pip on Python 2 will try to install this.
your code._

Expose Python 3 requirement in setup.py

---

.coveragerc
.github/workflows/test.yml

Little clean-up of the GitHub workflow and added submission of coverage reports to CodeCov.
your code._

Submit coverage reports to CodeCov

---

.github/workflows/test.yml
tox.ini

See https://github.com/django/django/pull/14048
your code._

ci: Django switched main Git branch to main

---

.github/workflows/test.yml
tox.ini

Test against Django 3.2, see https://github.com/python-social-auth/social-app-django/pull/314
your code._

ci: Add Django 3.2 to test matrix

---

social_django/__init__.py
social_django/apps.py
social_django/config.py

Fix deprecation warnings with Django 3.2+
your code._

Django 3.2+ compatibility

---

social_django/storage.py
social_django/strategy.py
tests/test_admin.py
tests/test_models.py
tests/test_strategy.py
tests/test_views.py

One cannot assume that the default manager for an app's user model is named `objects`. See https://docs.djangoproject.com/en/3.1/topics/db/managers/#default-managers .
To reproduce, create an app with a custom user model:
```
class CustomUser(AbstractUser):
manager = UserManager()
objects = None
class Meta:
default_manager_name="manager"
base_manager_name="manager"
```
In my app, we have a custom user model with a _default_manager other than `objects`: 
your code._
I pointed my app at this fork + …

Use _default_manager instead of objects

---

.github/workflows/test.yml
tox.ini

This PR changes CI to run tests on weekly basis to make sure we detect breakages in Django main as soon as possible. Also removes Django 3.0 and 3.1 as their are no longer supported.

CI: run tests on weekly basis

---

.github/workflows/test.yml
tox.ini

Add Python 3.10 and Django 4.0
your code._

ci: Add Python 3.10 and Django 4.0

---

.gitignore

Running the tests locally, I see some `.coverage.*` files generated, which come from using Coverage's parallel mode. These should be ignored in Git alongside the non-parallel file `.coverage`.
your code._
n/a

Git ignore parallel coverage files

---

.github/workflows/test.yml
tox.ini

Add Django 4.1 to the test matrix in tox and github actions. Also simplify the tox configuration by switching `django-<V>` to `django<V>`, which allows tox to treat the whole thing as a tag which can be selected on in the `deps` section.
your code._
n/a

ci: Add Django 4.1

---

social_django/middleware.py

Currently, defining `RAISE_EXCEPTIONS=False` in settings  has no effects if `DEBUG = True`.
This minor modification makes it possible to force the value to `False` in `DEBUG`, 
and will affect only env with `DEBUG = True`
your code._

Fix RAISE_EXCEPTIONS handling in SocialAuthExceptionMiddleware

---

.github/workflows/test.yml
.pre-commit-config.yaml
setup.py
tox.ini

- add 3.10 and 3.11
- drop 3.6
- fixes CI failures
your code._

deps: Update supported Python versions

---

setup.py

Presumably the project is considered stable by now.
your code._
n/a

Switch PyPI status classifier to Production/Stable

---

.github/workflows/test.yml
tox.ini

The main branch of Django now requires Python 3.10.
your code._

tox: Update Django main deps, add Django 4.2

---

.github/dependabot.yml

ci: Enable dependabot to automate github actions version upgrades

---

setup.cfg

Flake8 now passes on pre-commit.  Setting a `max-line-length` and then ignoring all long lines (`E501`) is a bad idea.  Instead, set the `max-line-length` to allow tests to pass and then decrease it over time to an acceptable value.
your code._
Any other information that is important to this PR such as …

Get flake8 working again

---

requirements-dev.txt

Upgrade pre-commit

---

.github/workflows/ruff.yml
.pre-commit-config.yaml
pyproject.toml
setup.cfg

Related to python-social-auth/social-core#768
your code._

pre-commit: Replace flake8, isort, and pyupgrade with ruff

---

.landscape.yaml

Like python-social-auth/social-core#762
your code._

Landscape CI is no longer being used

---

CHANGELOG.md
social_django/__init__.py

Release 5.1.0

---

.github/workflows/test.yml
requirements.txt
tox.ini

This allows to earlier catch issues like
https://github.com/python-social-auth/social-core/issues/773
your code._

ci: Test against current social-core

---

.pre-commit-config.yaml
requirements-dev.txt

This ensures consistent ordering of requirements.txt files.
Seems like I've accidentally included that in https://github.com/python-social-auth/social-app-django/pull/438.
your code._
the component looks before and after the …

ci: Include requirements-txt-fixer

---

CHANGELOG.md
requirements.txt
social_django/__init__.py

Release 5.2.0

---

tests/test_migrations.py

This part was missed when fixing #429, extracted from #396.
your code._

tests: Add test to detect missing migrations

---

requirements-dev.txt

The package was dropped from PyPI.
your code._

deps: Remove codecov

---

social_django/admin.py

I just wanted to display `created` and `modified` fields in admin to make it easier to debug potential problems.
Don't think tests are needed for this, but I might try to add some if required.

admin: display created and modified fields

---

.github/workflows/test.yml
setup.py
tox.ini

Add official support for Django 5 (and Python 3.12)
Update test matrix based on [Django's official supported versions](https://docs.djangoproject.com/en/4.2/faq/install/#what-python-version-can-i-use-with-django)
your code._

Support Django 5.0 (and python 3.12)

---

.github/workflows/test.yml
docker-compose.yml
setup.py
tox.ini

Drop support for Python 3.7 and Django 4.0 which are no longer supported upstream.
your code._

deps: Drop support for unsupported Python and Django

---

social_django/admin.py

This makes the code easier to read.
your code._

admin: use decorator syntax

---

social_django/migrations/0013_migrate_extra_data.py

This makes it more friendly to huge databases.
Fixes #501
your code._

migrations: optimize extra_data migration

---

CHANGELOG.md
requirements-dev.txt
social_django/__init__.py

Version bump 5.4.0
your code._

Version bump 5.4.0

---

CHANGELOG.md
social_django/__init__.py

Version bump 5.4.1

---

CHANGELOG.md
social_django/__init__.py

Release 5.4.2

---

.github/workflows/test.yml
tox.ini

This is what it currently requires.
your code._

fix(ci): test django main only on Python 3.12+

---

.github/workflows/test.yml
tox.ini

test against Django 5.1 and 5.2
your code._

chore: test against Django 5.1 and 5.2

---

requirements-dev.txt
requirements.txt

Using pyproject.toml for some time instead.
your code._

chore: remove requirements files

---

tox.ini

chore: update tox envlist

---

CHANGELOG.md
pyproject.toml

chore: Version bump 5.4.3

---

.github/workflows/test.yml
pyproject.toml
tox.ini

In case somebody wants to use that, older versions are available, but we will not keep maintaining the compatibility in the future.

chore(deps): drop support for Django versions not supported upstream

---

social_django/migrations/0009_auto_20191118_0520.py

It is needed on some database backends.
Fixes #268

fix(migrations): add default to modified timestamp

---

MANIFEST.in
pyproject.toml

fix: corrected sdist content

---

social_django/context_processors.py
social_django/fields.py

This is no longer needed with Django >= 4.2.

chore: drop old Django compatibility code

---

CHANGELOG.md
pyproject.toml

chore: Version bump 5.5.0

---

social_django/strategy.py

The whole pipeline relies that the user is None in this case.

fix: do not use AnonymousUser as registering user

---

CHANGELOG.md
pyproject.toml

To push out https://github.com/python-social-auth/social-app-django/pull/729 fast as this is a regression introduced in 5.5.0.

chore: Version bump 5.5.1

---

.github/workflows/scorecard.yml

Add Scorecard workflow for supply-chain security

---

.github/workflows/test.yml
tox.ini

Utilize uv for better caching and faster installation times.

chore(ci): sync with social-core

---

social_django/storage.py

Implement generic filter_users method and reuse it.

chore: factor out user filtering
