social_django/managers.py, social_django/models.py
This pull request will solve #11.
To test the pull request with my broken app I had to install https://github.com/python-social-auth/social-app-django/ and https://github.com/python-social-auth/social-core.
~~~
$ git clone https://github.com/python-social-auth/social-core.git
$ cd social-core
$ python setup.py install
$ cd ..
$ git clone https://github.com/python-social-auth/social-app-django.git
$ cd social-app-django
$ python setup.py install
~~~
I had to replace 
~~~
'social.apps.django_app.context_processors.backends',
~~~
with
~~~
'social_django.context_processors.backends',
~~~
and
~~~
url('', include('social.apps.django_app.urls', namespace='social')),
~~~
with
~~~
url('', include('social_django.urls', namespace='social')),
~~~
on my broken app.
=> Add explicit app_label

social_django/migrations/0005_auto_20160727_2333.py
Fixes #16, #9, #13 
This migration did never exist for `default` app as old python-social-auth didn't ship it and the new one did not replace. Replacing it now leads to Django seeing it as partially applied...
=> Remove replacement of non existing migration

social_django/strategy.py
In Django 1.10 and olders, request is part of kwargs, by throwing it
away in Django 1.11 we make it unavailable to the pipeline.
This is followup for #24
=> Pass request in kwargs if we have received it

tests/test_models.py
Wrote these tests while investigating a problem I had while writing a custom backend.
While implementing a custom Backend, I had an error in the `do_complete()` function where the `social_user` was `None`, shortly after social_core did `social_user = user.social_user`.
After a bit of research, it was because my backend needed to override `ID_KEY`. The error wasn't clearly raised and [the docs](http://python-socialauth.readthedocs.io/en/latest/backends/implementation.html#shared-attributes) do not mention this caveat.
From what I gathered, something is setting the `social_user` attribute on the request's user. These tests are showing that the attribute isn't normally set.
Would you accept a PR in the core or in the docs to try to make this caveat more obvious? That would have saved me a …
=> Write a few tests for models

tox.ini
Django 1.11 [is progressing](https://www.djangoproject.com/weblog/2017/jan/17/django-111-alpha-1/), with the current setup the tests for Django 1.10 are going to run against 1.11 when released.
=> Tests: install django 1.10, not 1.11

.travis.yml, CHANGELOG.md, dev-requirements.txt, social_django/views.py, tests/test_views.py, tox.ini
Implements #53.
This pull request adds a configurable setting `MAX_SESSION_LENGTH` which, when set, allows service providers to set the maximum length of time that a user who logs in via social auth may remain logged in. If set to 0, the session will expire on browser close. If not set, then either the session length received from the social auth provider (if available) or the platform default session length will be used.
This pull request also makes some small tweaks to the testing framework; it consolidates requirements into a single `dev-requirements.txt` file and references that file in `.travis.yml` and in `tox.ini`.
Note: The current version of `social-core` does not wipe `partial_pipeline_token` from the browser session on completion of the pipeline, but in the past, the pipeline …
=> Allow configurable maximum session length

social_django/urls.py
Accept only integers in the URL as association ID, otherwise it fails
later.
Otherwise you end up with ValueError later:
```
File "social_core/pipeline/disconnect.py" in allowed_to_disconnect
6.     if not user_storage.allowed_to_disconnect(user, name, association_id):
File "social_django/storage.py" in allowed_to_disconnect
25.             qs = cls.objects.exclude(id=association_id)
File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py" in manager_method
85.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in exclude
803.         return self._filter_or_exclude(True, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in _filter_or_exclude
812. …
```
=> Association ID is integer

social_django/fields.py
Seems like support to use django.contrib.postgres.fields.JSONField as base Field class for extra_data will be useful, because postgres JSONField usage provides ability to make complex queries over extra_data
=> Added support to use django.contrib.postgres.fields.JSONField

.travis.yml, tox.ini
In order to prepare for Django 2.0 (https://github.com/python-social-auth/social-app-django/issues/6), update the build matrix to run tests on django master with allowed failures.
While I'm at it, I thought I would update it to run on Python 3.6 as well.
=> Run tests against Python 3.6 and Django master

social_django/fields.py
=> Django 2.0 support: don't use the removed _get_val_from_obj()

social_django/context_processors.py, tests/test_context_processors.py
Since it can handle unicode out of the box
https://docs.djangoproject.com/en/1.11/_modules/django/utils/http/#urlquote
Python 3 is not affected but for 2.7 it can cause problems.
Will fix #60
=> Use urlquote instead of built-in quote 

social_django/compat.py
`django.core.urlresolvers` is deprecated since version 1.10
https://docs.djangoproject.com/en/1.10/ref/urlresolvers/#module-django.urls
With this simple commit `django.urls` will be used if present avoiding very annoying warnings with Django >= 1.10
=> More pythonic way to handle urlresolvers deprecation

social_django/storage.py
If model have not 'usrername' field because User.USERNAME_FIELD is "email" then user creation fails. This PR should fix that issue
=> handle models that use "email" as username_field 

social_django/compat.py
https://docs.djangoproject.com/en/dev/releases/1.9/#field-rel-changes
this silences the deprecation warnings
=> field.rel was renamed in django 1.9

social_django/fields.py
Fixes:
> …/django/db/models/sql/compiler.py:998:
> RemovedInDjango30Warning: Remove the context parameter from
> JSONField.from_db_value(). Support for it will be removed in Django 3.0.
Fixes https://github.com/python-social-auth/social-app-django/issues/155
=> JSONField.from_db_value: remove context kwarg

social_django/storage.py
[Django documents](https://docs.djangoproject.com/en/2.2/topics/db/transactions/#django.db.transaction.atomic) that without a `using` parameter, `transaction.atomic` will use the `default` database. Not everyone may store their user objects in the default database though, so determine _what_ database should be used and specify it in the `using` parameter.
=> When using transaction.atomic, use the right db

CONTRIBUTING.md
The "Github pull request documentation" link is broken. Suggesting linking to "Creating a pull request".
=> Broken link at Additional Resources

CHANGELOG.md, social_django/storage.py
Addresses: https://github.com/python-social-auth/social-core/issues/383
Part of this PR: https://github.com/python-social-auth/social-core/pull/384 as detailed in this comment: https://github.com/python-social-auth/social-core/pull/384/files#r308203030
=> feat(DjangoNonceMixin): implement 'get' and 'delete' class methods

social_django/migrations/0009_uid_db_index.py, social_django/models.py
in case unique_together does add (function as) an index
(e.g. Postgres) it will be a multiple column index. If you want
one of the columns to be indexed individually you need to specify
db_index=True.
Backgroud: we've got an app which already handles social login via GitHub and will also start receiving GitHub webhooks. The only solid piece of identifier is the GitHub user ID which is the `uid` field.
=> Add db_index=True to UserSocialAuth.uid field

social_django/strategy.py, tests/settings.py, tests/test_strategy.py, tox.ini
Fixes #222
This also removes unsupported djangoes from `tox.ini`, because the test I added won't pass on Django 1.10 or lower, and the README states: 
> This project will focus on the currently supported Django releases as stated on the Django Project Supported Versions table.
... which is currently 1.11, 2.1, 2.2.
=> Fix TypeError on Django 2.1 when continuing partial pipelines

social_django/urls.py
The former was a deprecated alias for `django.urls.re_path` which allowed the use
of regular expressions as part of the route, while `django.urls.path` instead
makes use of converters to parse specific parts of the URL in an easier-to-read
format.
=> Switch from deprecated django.conf.urls.url to django.urls.path

social_django/context_processors.py, social_django/utils.py
If you're writing unit tests that test various options for
AUTHENTICATION_BACKENDS using e.g.
@override_settings(AUTHENTICATION_BACKENDS=...) or `with
self.settings(...)`, that works great in Django in general.
However, the first such test that interacts with python-social-auth
enough to cause utils.py to be imported will fix the value of
AUTHENTICATION_BACKENDS used by social-auth for the rest of the
process' lifetime.
As a result, if one first accesses it with a smaller/restrictive list
of backends, and then tries to use it with a larger list later, one
gets a 404 "Backend Not Found" error in those later accesses. So it
manifested for us as unit tests passing or failing depending on
whether our one test that sets a short list of backends ran early or
late.
The fix is simply to access …
=> utils: Stop fixing AUTHENTICATION_BACKENDS unnecessarily.

CHANGELOG.md, social_django/fields.py
**Update 2020-09-06: I am not using this project anymore (due an outside reason, this project is fine). If there are edits needed that the maintainer can't add, feel free to fork [my branch](https://github.com/tony/social-app-django/tree/fix-jsonfield-import) / make your own branch and PR it. I apologize about this!**
Django 3.1 has a universal JSONField in `django.db.models`.
It raises a deprecation warning for JSONField imported via
`django.contrib.postgres`. Django 4.x removes it completely.
Preserve compatibility with older versions, import via compat module.
Hopefully this preserves migration compatibility.
Fixes #265
Also adds django 3.0 and 3.1 to CI - ignores `master` (which can fail sporadically)
Add support for django 3.0 and 3.1 
Django 3.1 introduces JSONField support for all …
=> Update JSONField for django 3.1+

.gitignore, setup.cfg
It seems nose has not been used since 77a3ec42468640dd67086e6afba3375cb7ae8135, so these final references in configuration can be removed.
your code._
n/a
=> Remove references to nose testing framework

CHANGELOG.md, social_django/__init__.py
Release to fix #491
your code._
=> Version bump 5.3.0

social_django/fields.py
When setting JSONFIELD_CUSTOM the logic was importing under the wrong name with `Base` suffix raising `Import Error` as the module ended up having no `JSONField` to be imported.
Looks like due to a  recent change the JSONFieldBase` is no more needed.
=> Fix ImportError: cannot import name 'JSONField' from 'social_django.fields' when  JSONFIELD_CUSTOM is set

.gitignore, CHANGELOG.md, social_django/utils.py, social_django/views.py, tests/test_views.py
This PR introduces a new configuration and authentication behaviour when it is active and will require POST request during authentication
* Configuration key is `SOCIAL_AUTH_REQUIRE_POST: bool`,
* Error response if request method is not `POST`.
* https://github.com/python-social-auth/social-app-django/issues/486
* https://github.com/python-social-auth/social-app-django/issues/55
your code._
=> Add configuration to require POST only authentication requsts

social_django/context_processors.py, tests/test_context_processors.py
The `login_redirect` context-processor relies on `request.POST` data to retrive the redirect field value.
If by any means the django app is serving a malformed multipart request (ie: `Content-Type: multipart/form-data` without a proper form-boundary) it will raise a multipart error. Since this context-processor is advised to be used in the default template configuration it will cause a 500 response (internal server error) due to the un-catched exception.
=> Avoid raising errors on malformed POST data

social_django/models.py
The database collation might vary, so use safer comparing in Python.
your code._
=> models: make sure uid is compared case-sensitive

.github/workflows/test.yml, setup.py, tox.ini
Add support for python 3.13.
I've ran the tests locally using the 3.13rc3 and they passed
your code._
Completed as part of DjangoLondon's HacktoberFest: https://github.com/djangolondon/djangolondon.github.io/discussions/188
=> deps: Update supported Python versions

CHANGELOG.md, social_django/migrations/0013_migrate_extra_data.py
The `extra_data` json field migration `0013_migrate_extra_data.py` was not revertable since the `is_text_field` type check was throwing a TypeError since the first argument is an instance instead of a class. This error occurs only when reverting migrations on databases other than SQLite.
your code._
=> Fixed rollback of extra_data migration

social_django/views.py
Django 5.1 introduced the LoginRequiredMiddleware which flips around the defaults for view authentication which breaks the login views for apps that use the middleware.
This decorates the login views explicitly with login_not_required.
Fixes #713
=> Fix LoginRequiredMiddleware compatibility
